# Generated by Django 2.0.6 on 2018-06-22 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20180621_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='remark',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date'),
        ),
    ]
