# Generated by Django 2.0.6 on 2018-06-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20180622_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10, verbose_name='transaction'),
        ),
    ]
