# Generated by Django 2.0.6 on 2018-06-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20180622_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'get_latest_by': '-date', 'verbose_name': 'transaction', 'verbose_name_plural': 'transactions'},
        ),
        migrations.AddField(
            model_name='category',
            name='transaction_type',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10, null=True, verbose_name='transaction type'),
        ),
    ]
